[main]
font=monospace:size=8
line-height=13

prompt=">   "
layer=overlay
terminal=foot

dpi-aware=yes

# Sizes & Padding
width=50
horizontal-pad=40
vertical-pad=20
inner-pad=0

icons-enabled=true
icon-theme=Arc
image-size-ratio=0.4

[colors]
background=1e1e2eff
text=cdd6f4ff
match=f38ba8ff
selection=585b70ff
selection-text=cdd6f4ff
border=b4befeef
