########################################################################
# Terminal Title Bar
########################################################################

set -g set-titles on
set -g set-titles-string "#W #{?#{==:#W,nvim},» #T,}"

#S	Name of session
#I	Index of window
#P	Index of pane
#W	Name of window
#F	Window flags
#h	Hostname of local host without domain
#H	Hostname of local host
#D	Unique pane ID
#T	Title of pane
