monitor_exclusive = true
position = "top"
height = 32

[[start]]
type = "workspaces"
all_monitors = false

[[end]]
type = "script"
cmd = "i3status-rs ~/.config/i3status-rust/config.toml"
interval = 0 # 0 means it stays open and listens to the stream
