########################################################################
# Tmux default config
########################################################################

###
### Sane Defaults
###

# Do not start a login shell (faster loading, keeps PATH predictable)
set -g default-command "${SHELL}"

# Address vim mode switching delay. 10ms is recommended for responsiveness
# without breaking escape sequences.
# http://superuser.com/a/252717/65504
set -sg escape-time 10

# Increase scrollback history to 10,000 lines.
set -g history-limit 10000

# Terminals & TrueColor (Optimized for Alacritty/Foot)
set -g default-terminal "tmux-256color"
set -as terminal-features ",*:RGB"

# Focus events enabled for terminals that support them.
set -g focus-events on

# Rather than constraining window size to the maximum size of any client
# connected to the *session*, constrain window size to the maximum size of any
# client connected to *that window*.
# Super useful when using "grouped sessions" and multi-monitor setup
setw -g aggressive-resize on


###
### Window / Pane Settings
###

# Start Window index (Tabs) at 1 instead of 0
set -g base-index 1

# Start Panes at 1 insteaad of 0
setw -g pane-base-index 1

# Renumber windows sequentially after closing any of them
set -g renumber-windows on

# Set Auto Rename of Windows base on command
setw -g automatic-rename on

# Monitor activity in other windows
setw -g monitor-activity on
set -g visual-activity off # Set to off to avoid annoying popups; status bar will still highlight


###
### Source configs
###
source-file ~/.config/tmux/conf.d/keys.conf
source-file ~/.config/tmux/conf.d/mouse.conf
source-file ~/.config/tmux/conf.d/statusbar.conf
source-file ~/.config/tmux/conf.d/theme.conf
source-file ~/.config/tmux/conf.d/titlebar.conf
