[theme]
theme = "native"

[icons]
icons = "material-nf"

[[block]]
block = "cpu"
interval = 2
format = " $icon $frequency ($utilization) "

[[block]]
block = "temperature"
format = " $icon $max "

[[block]]
block = "memory"
format = " $icon $mem_used.eng(w:3, p:G) ($mem_used_percents) "

[[block]]
block = "disk_space"
path = "/"
format = " $icon $used.eng(w:2)/$available.eng(w:2) "

[[block]]
block = "custom"
command = "echo '\uf0ac ' `curl -s --connect-timeout 2 --max-time 3 ip-api.com/line/?fields=query`"
interval = 10

[[block]]
block = "net"
# If 'wlan0' fails, comment out the device line to auto-detect
device = "tun0"
format = " $icon $ip "
missing_format = ""
format_alt = " $icon $ip / $ipv6 / NS: $nameserver "
[block.theme_overrides]
idle_bg = "#A86F6F"
idle_fg = "#FFFFFF"


[[block]]
block = "net"
# If 'wlan0' fails, comment out the device line to auto-detect
device = "wlan0"
format = " $icon $ssid ($signal_strength) "
format_alt = " $icon $ip ($bitrate) "

[[block]]
block = "custom"
command = ''' i3status-rs-bluetooth.sh '''
interval = 2
json = true
[block.theme_overrides]
warning_fg = "#A86F6F"
idle_fg = "#80b3ff"
good_fg = "#005ce6"

[[block]]
block = "sound"
[block.theme_overrides]
warning_fg = "#A86F6F"

[[block]]
block = "sound"
driver = "pulseaudio"
device_kind = "source" # This targets your microphone
[block.theme_overrides]
warning_fg = "#A86F6F"

#[[block]]
#block = "backlight"

[[block]]
block = "battery"
driver = "sysfs"
interval = 1
#format = " $icon $percentage {$time_remaining} $power "
full_format = " $icon $percentage {($time_remaining.dur(hms:true, min_unit:m))|}"
not_charging_format = " a asd "
charging_format = " $icon $percentage "
missing_format = " "
[block.theme_overrides]
warning_fg = "#A86F6F"
critical_bg = "#A86F6F"
critical_fg = "#FFFFFF"

[[block]]
block = "time"
interval = 60
format = "  $timestamp.datetime(f:'(%V) %a, %d.%m.%Y') "

[[block]]
block = "time"
interval = 60
format = " $timestamp.datetime(f:'%R') "
[block.theme_overrides]
idle_fg = "#ffffff"
